version: "3.1"
services:
    www:
        build: .
        ports:
            - "80"
        networks:
          - nginx-proxy
        environment:
          VIRTUAL_HOST:
          LETSENCRYPT_HOST:
          LETSENCRYPT_EMAIL:
        deploy:
          restart_policy:
            condition: on-failure
networks:
  nginx-proxy:
    external: true
